# -*- coding: utf-8 -*-
"""UTS_Comvis2318018.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQ0LiyqQODS-aNZqItNpyQNdWFSZH7u_

# =======================================
# 1. IMPORT LIBRARY & MENGHUBUNGKAN DRIVE
# =======================================
"""

import cv2
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from skimage.feature import graycomatrix, graycoprops

from google.colab import drive
drive.mount('/content/drive')

"""# ====================================
# 2. LOAD DATASET & INISIALISASI LABEL
# ====================================
"""

image_dir = "/content/drive/MyDrive/Uts_Comvis/Images"

X, y, filenames = [], [], []

for img_name in os.listdir(image_dir):
    img_path = os.path.join(image_dir, img_name)
    img = cv2.imread(img_path)

    if img is None:
        continue

    name = img_name.lower()

    if "unriped" in name:
        label = 0
    elif "riped" in name:
        label = 1
    elif "busuk" in name:
        label = 2
    else:
        continue

    X.append(img)
    y.append(label)
    filenames.append(img_name)

print("Total data:", len(X))

"""# ====================================
# 3. Visualisasi Jumlah Data
# ====================================
"""

label_names = ["Tidak Matang", "Matang", "Busuk"]

plt.figure(figsize=(6,4))
sns.countplot(x=y)
plt.xticks([0,1,2], label_names)
plt.title("Distribusi Dataset Tomat")
plt.xlabel("Kelas")
plt.ylabel("Jumlah Data")
plt.show()

"""# ========================
# 4. PREPROCESSING
# ========================
"""

def remove_background(img):
    img = cv2.resize(img, (64, 64))
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    lower_red1 = np.array([0,70,50])
    upper_red1 = np.array([10,255,255])
    lower_red2 = np.array([170,70,50])
    upper_red2 = np.array([180,255,255])

    mask_red = cv2.bitwise_or(
        cv2.inRange(hsv, lower_red1, upper_red1),
        cv2.inRange(hsv, lower_red2, upper_red2)
    )

    lower_green = np.array([35,50,50])
    upper_green = np.array([85,255,255])
    mask_green = cv2.inRange(hsv, lower_green, upper_green)

    lower_dark = np.array([0,0,30])
    upper_dark = np.array([180,255,120])
    mask_dark = cv2.inRange(hsv, lower_dark, upper_dark)

    mask = cv2.bitwise_or(mask_red, mask_green)
    mask = cv2.bitwise_or(mask, mask_dark)

    result = cv2.bitwise_and(img, img, mask=mask)

    coords = cv2.findNonZero(mask)
    if coords is not None:
        x, y_, w, h = cv2.boundingRect(coords)
        result = result[y_:y_+h, x:x+w]

    return cv2.resize(result, (64, 64))

X_processed = [remove_background(img) for img in X]

# ========================
# VISUALISASI PREPROCESSING
# ========================
plt.figure(figsize=(8,4))

plt.subplot(1,2,1)
plt.imshow(cv2.cvtColor(X[0], cv2.COLOR_BGR2RGB))
plt.title("Sebelum")
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(cv2.cvtColor(X_processed[0], cv2.COLOR_BGR2RGB))
plt.title("Sesudah (Background Hilang)")
plt.axis('off')

plt.show()

"""# ========================
# 5. FEATURE EXTRACTION
# ========================
"""

def extract_features(img):
    mask = np.any(img != [0,0,0], axis=-1)
    pixels = img[mask] if np.any(mask) else img.reshape(-1,3)

    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hsv_pixels = hsv[mask]

    hist = cv2.calcHist([hsv], [0,1,2], mask.astype(np.uint8),
                        [8,8,8], [0,256,0,256,0,256])
    hist = cv2.normalize(hist, hist).flatten()

    mean_rgb = np.mean(pixels, axis=0)
    mean_hsv = np.mean(hsv_pixels, axis=0)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray_pixels = gray[mask]

    brightness = np.mean(gray_pixels)
    std_color = np.std(pixels)
    saturation = np.mean(hsv_pixels[:,1])

    edges = cv2.Canny(gray, 100, 200)
    edge_density = np.mean(edges[mask])

    extra = np.array([brightness, std_color, saturation, edge_density])

    glcm = graycomatrix(gray, distances=[1,2],
                        angles=[0, np.pi/4],
                        levels=256, symmetric=True, normed=True)

    texture = np.array([
        graycoprops(glcm, 'contrast').mean(),
        graycoprops(glcm, 'homogeneity').mean(),
        graycoprops(glcm, 'energy').mean(),
        graycoprops(glcm, 'correlation').mean()
    ])

    return np.hstack([hist, mean_rgb, mean_hsv, extra, texture])

# 🔥 FIX PENTING
X_features = np.array([extract_features(img) for img in X_processed])
y = np.array(y)

print("Shape fitur:", X_features.shape)

"""# ========================
# 6. SCALING
# ========================
"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_features)

"""# ========================
# 7. SPLIT DATA
# ========================
"""

X_train, X_test, y_train, y_test, img_train, img_test, file_train, file_test = train_test_split(
    X_scaled, y, X, filenames, test_size=0.2, random_state=42
)

"""# ========================
# 8. TRAIN MODEL
# ========================
"""

knn = KNeighborsClassifier(n_neighbors=5, weights='distance')
knn.fit(X_train, y_train)

"""# ========================
# 9. EVALUASI
# ========================
"""

y_pred = knn.predict(X_test)

label_names = ["Tidak Matang", "Matang", "Busuk"]
jumlah_salah = np.sum(y_pred != y_test)
jumlah_benar = np.sum(y_pred == y_test)

print("Jumlah benar:", jumlah_benar)
print("Jumlah salah:", jumlah_salah)
print("Akurasi:", accuracy_score(y_test, y_pred))
print(" ")
print(classification_report(y_test, y_pred, target_names=label_names))


for i, name in enumerate(label_names):
    idx = (y_test == i)
    if np.sum(idx) > 0:
        acc_class = np.mean(y_pred[idx] == y_test[idx])
        print(f"Akurasi {name}: {acc_class:.2f}")
    else:
        print(f"Akurasi {name}: Tidak ada data di test set")

"""# ========================
# 10. Perhitungan KNN (Distance)
# ========================
"""

def show_knn_3_samples(k=5):
    label_names = ["Tidak Matang", "Matang", "Busuk"]

    indices = []

    # ambil 1 dari tiap kelas
    for label in [0, 1, 2]:
        for i in range(len(y_test)):
            if y_test[i] == label:
                indices.append(i)
                break
    fig = plt.figure(figsize=(15,10))

    for idx, index in enumerate(indices):
        test_point = X_test[index]

        distances = []
        for i in range(len(X_train)):
            dist = np.linalg.norm(test_point - X_train[i])
            distances.append((i, dist, y_train[i]))

        distances = sorted(distances, key=lambda x: x[1])
        neighbors = distances[:k]

        df = pd.DataFrame(neighbors, columns=["Index", "Distance", "Label"])
        df["Distance"] = df["Distance"].apply(lambda x: round(x, 3))
        df["Label"] = df["Label"].apply(lambda x: label_names[x])

        votes = [n[2] for n in neighbors]
        unique, counts = np.unique(votes, return_counts=True)
        final = unique[np.argmax(counts)]
        actual = y_test[index]

        # gambar
        ax_img = fig.add_subplot(3,2,idx*2+1)
        ax_img.imshow(cv2.cvtColor(img_test[index], cv2.COLOR_BGR2RGB))

        color = "green" if final == actual else "red"

        ax_img.set_title(
            f"{idx+1}. Pred: {label_names[final]} | Actual: {label_names[actual]}",
            color=color
        )
        ax_img.axis('off')

        # tabel
        ax_tbl = fig.add_subplot(3,2,idx*2+2)
        ax_tbl.axis('off')

        table = ax_tbl.table(
            cellText=df.values,
            colLabels=df.columns,
            loc='center',
            cellLoc='center'
        )

        table.auto_set_font_size(False)
        table.set_fontsize(10)
        table.scale(1,1.5)

    plt.suptitle("Visualisasi Proses KNN (3 Data Test)", fontsize=16)
    plt.tight_layout()
    plt.show()


# ✅ panggil di sini (di luar fungsi)
show_knn_3_samples(k=5)

"""# ========================
# 11. CONFUSION MATRIX
# ========================
"""

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_names,
            yticklabels=label_names)
plt.title("Confusion Matrix")
plt.show()

"""# ========================
# 12. ERROR ANALYSIS
# ========================
"""

for i in range(len(X_test)):
    if y_pred[i] != y_test[i]:
        print(f"{file_test[i]} → Pred: {label_names[y_pred[i]]} | Actual: {label_names[y_test[i]]}")

"""# ========================
# 13. EXPORT KE EXCEL
# ========================
"""

data = []

for i in range(len(X_test)):
    status = "BENAR" if y_pred[i] == y_test[i] else "SALAH"

    data.append({
        "filename": file_test[i],
        "prediction": label_names[y_pred[i]],
        "actual": label_names[y_test[i]],
        "status": status
    })

df = pd.DataFrame(data)

save_path = "/content/drive/MyDrive/Uts_Comvis/hasil_evaluasi_tomat_new.xlsx"
df.to_excel(save_path, index=False)

print("File disimpan:", save_path)